### ISSUE TITLE
refactor: Prepare for 1.0.0 release

### ISSUE THREAD

**Issue by qwinters** [qwinters/course-repo-template#9]
Website template should be formatted around combination of PDF notes + lecture by lecture posts for outlines

File structure: 
```yaml
course-repo-template:
    .github: 
        - workflows # workflows for automation
        - configs # configs for auto assignment + changelog
        - settings.yml # store settings for labels / issues in here
    common:
        - preamble.tex
        - macros.tex # custom macros for the individual course, default empty
    gh-pages: 
        - _layouts: [ default.html, post.html ] # etc
        - _config.yml # where config values for navigation goes
        - index.md # default template for landing page
        - notes.pdf
        - hwk01.pdf # etc 
    homework:
        - homework01:
            - problems: [ problem01.tex ] # etc.
            - hwk01.tex
    lectures:
        - lecture-01.md # contains raw lecture notes in real time (outline of material)
    notes:
        - chapters:
            - chapter01.tex
            - chapter01: [ section01.tex ] # etc 
        - references.bib
        - notes.tex
    .chktexrc
    .gitignore
    README.md
    CHANGELOG.md
    HOWTO.md
    LICENSE.txt
```

TODOs to accomplish this refactor
- [x] refactor: Reformat file structure
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #18
